sudo: required
language: node_js
node_js:
  - "0.12"

before_install:
  - curl -L https://git.io/ejPSng | /bin/sh
  - npm install -g spacejam
  - meteor npm install


env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8


script:
  - spacejam test-packages ./